import React, { useEffect } from 'react'
import Head from 'next/head'
import Navbar from "../components/Navbar"
import Sidebar from "../components/Sidebar"
import { useSelector, useDispatch } from 'react-redux'
import { useRouter } from 'next/router'
import { isLoggedIn } from '../reducers/login_reducer'

export default function Home({ cookies }) {
  const router = useRouter()
  const { user } = useSelector(state => state.login)
  const dispatch = useDispatch()
  const cookieValue = cookies.user

  useEffect(() => {
    if (!cookieValue) {
      router.push("/login")
    } else {
      dispatch(isLoggedIn(cookieValue))
    }
  }, [])

  return (
    <div className="bg-gray-300 text-white h-screen">
      <Head>
        <title>SIM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Sidebar />
      </main>

    </div>
  )
}

export const getServerSideProps = async (context) => {
  const cookies = context.req.cookies
  return {
    props: {
      cookies
    }
  }
}
